/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductDAO;

/**
 *
 * @author dugwi731
 */
public class MainMenu extends javax.swing.JFrame {
	
	private final ProductDAO dao; 

	/**
	 * Creates new form MainMenu
	 */
	public MainMenu(ProductDAO dao) {
		this.dao = dao;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      buttonExit = new javax.swing.JButton();
      buttonAdd = new javax.swing.JButton();
      buttonView = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("Product Administration");
      jLabel1.setName("jLabel1"); // NOI18N

      buttonExit.setText("Exit");
      buttonExit.setName("buttonExit"); // NOI18N
      buttonExit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonExitActionPerformed(evt);
         }
      });

      buttonAdd.setText("Add a new product");
      buttonAdd.setName("buttonAdd"); // NOI18N
      buttonAdd.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonAddActionPerformed(evt);
         }
      });

      buttonView.setText("View products");
      buttonView.setName("buttonView"); // NOI18N
      buttonView.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonViewActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
               .addComponent(buttonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(buttonView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(buttonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addGap(36, 36, 36)
            .addComponent(buttonAdd)
            .addGap(54, 54, 54)
            .addComponent(buttonView)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
            .addComponent(buttonExit)
            .addGap(43, 43, 43))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
      // TODO add your handling code here:
		System.exit(0);
   }//GEN-LAST:event_buttonExitActionPerformed

   private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
      // TODO add your handling code here:
		// create the dialog instance
		// the first parameter the parent window, and the second is the modal status
		ProductEditor productDialog = new ProductEditor(this, true, dao);
		// centre the dialog on the parent window
		productDialog.setLocationRelativeTo(this);
		// make the dialog visible
		productDialog.setVisible(true);
   }//GEN-LAST:event_buttonAddActionPerformed

   private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
      // TODO add your handling code here:
		// the first parameter the parent window, and the second is the modal status
		ProductViewer viewerDialog = new ProductViewer(this, true, dao);
		// centre the dialog on the parent window
		viewerDialog.setLocationRelativeTo(this);
		// make the dialog visible
		viewerDialog.setVisible(true);
   }//GEN-LAST:event_buttonViewActionPerformed


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonAdd;
   private javax.swing.JButton buttonExit;
   private javax.swing.JButton buttonView;
   private javax.swing.JLabel jLabel1;
   // End of variables declaration//GEN-END:variables
}
