/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ProductDAO;
import dao.ProductJdbcDAO;
import domain.Product;
import helpers.SimpleListModel;
import java.util.Collection;
import javax.swing.JOptionPane;

/**
 *
 * @author dugwi731
 */
public class ProductViewer extends javax.swing.JDialog {
	
	private final ProductDAO dao;
	private SimpleListModel productsModel = new SimpleListModel();
	private SimpleListModel categoryModel = new SimpleListModel();

	/**
	 * Creates new form ProductViewer
	 */
	public ProductViewer(java.awt.Frame parent, boolean modal, ProductDAO dao) {
		super(parent, modal);
		this.dao = dao;
		initComponents();
		
		Collection<Product> productList = dao.getProducts();
		productsModel.updateItems(productList);
		listViewProducts.setModel(productsModel);

		Collection<String> categoryList = dao.getCategories();
		categoryModel.updateItems(categoryList);
		comboCategory.setModel(categoryModel);	
		
	} 

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      listViewProducts = new javax.swing.JList<>();
      buttonClose = new javax.swing.JButton();
      buttonEdit = new javax.swing.JButton();
      buttonDelete = new javax.swing.JButton();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      txtSearch = new javax.swing.JTextField();
      buttonSearch = new javax.swing.JButton();
      comboCategory = new javax.swing.JComboBox<>();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      listViewProducts.setName("listViewProducts"); // NOI18N
      jScrollPane1.setViewportView(listViewProducts);

      buttonClose.setText("Close");
      buttonClose.setName("buttonClose"); // NOI18N
      buttonClose.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonCloseActionPerformed(evt);
         }
      });

      buttonEdit.setText("Edit");
      buttonEdit.setName("buttonEdit"); // NOI18N
      buttonEdit.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonEditActionPerformed(evt);
         }
      });

      buttonDelete.setText("Delete");
      buttonDelete.setName("buttonDelete"); // NOI18N
      buttonDelete.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonDeleteActionPerformed(evt);
         }
      });

      jLabel1.setText("View Products");
      jLabel1.setName("jLabel1"); // NOI18N

      jLabel2.setText("Search by ID:");
      jLabel2.setName("jLabel2"); // NOI18N

      jLabel3.setText("Category Filter:");
      jLabel3.setName("jLabel3"); // NOI18N

      txtSearch.setName("txtSearch"); // NOI18N

      buttonSearch.setText("Search");
      buttonSearch.setName("buttonSearch"); // NOI18N
      buttonSearch.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            buttonSearchActionPerformed(evt);
         }
      });

      comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
      comboCategory.setName("comboCategory"); // NOI18N
      comboCategory.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboCategoryActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(buttonClose, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(18, 18, 18)
                  .addComponent(jLabel2)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtSearch)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(buttonSearch))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel3)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(comboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(txtSearch)
               .addComponent(buttonSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(comboCategory)
               .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(buttonClose)
               .addComponent(buttonEdit)
               .addComponent(buttonDelete))
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
      // TODO add your handling code here:
		dispose();
   }//GEN-LAST:event_buttonCloseActionPerformed

   private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_buttonEditActionPerformed

   private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
		// TODO add your handling code here:
		Product selectedProduct = listViewProducts.getSelectedValue();

		if (listViewProducts.isSelectionEmpty() == false) {
			int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
			if (result == JOptionPane.YES_OPTION) {
				// user clicked yes so perform the action
				dao.removeProduct(selectedProduct);
				productsModel.updateItems(dao.getProducts());
			}
		}
   }//GEN-LAST:event_buttonDeleteActionPerformed

   private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
      // TODO add your handling code here:
		String result = txtSearch.getText();
		productsModel.updateItems(dao.searchById(result));
   }//GEN-LAST:event_buttonSearchActionPerformed

   private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
      // TODO add your handling code here:
		Object result = comboCategory.getSelectedItem();
		productsModel.updateItems(dao.filterByCategory((String) result));
		listViewProducts.setModel(productsModel);
   }//GEN-LAST:event_comboCategoryActionPerformed

	
	
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton buttonClose;
   private javax.swing.JButton buttonDelete;
   private javax.swing.JButton buttonEdit;
   private javax.swing.JButton buttonSearch;
   private javax.swing.JComboBox<String> comboCategory;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JList<Product> listViewProducts;
   private javax.swing.JTextField txtSearch;
   // End of variables declaration//GEN-END:variables
}
